version: '2'

services:
  elasticsearch:
    environment:
      bootstrap.memory_lock: "false"
      ES_JAVA_OPTS: ""
    ulimits:
      memlock:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

  nutch:
    volumes:
      - ./nutch/nutch-site.xml:/root/nutch/conf/nutch-site.xml:ro
      - ./nutch/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt:ro
      - ./nutch/seed.txt:/root/nutch/urls/seed.txt:ro
    tty: true
    command: bash
