version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    environment:
      cluster.name: elasticsearch
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - cluster
    ports:
      - 9200:9200

  es-init:
    build:
      context: ./es-init
    image: localhost:5000/es-init:nutch
    environment:
      ES_HOST: elasticsearch
      TIME_OUT: 120
    depends_on:
      - elasticsearch
    networks:
      - cluster

  nutch:
    build:
      context: ./nutch
    image: localhost:5000/nutch:elastic-5.3.0
    container_name: nutch
    volumes:
      - nutch-data:/root/nutch/data
    depends_on:
      - elasticsearch
    networks:
      - cluster

  searchkit:
    build:
      context: ./searchkit
    image: localhost:5000/searchkit:0.1
    container_name: searchkit
    depends_on:
      - elasticsearch
    networks:
      - cluster
    ports:
      - 3000:3000

volumes:
  elastic-data:
    driver: local
  nutch-data:
    driver: local

networks:
  cluster:
    driver: bridge
