version: '2'

services:
  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300

  es-init:
    # command: "echo Skipped"
    volumes:
      - ./es-init/init-elastic:/app/init-elastic
      - ./es-init/mapping.json:/app/mapping.json

  nutch:
    volumes:
      - ./nutch/nutch-site.xml:/root/nutch/conf/nutch-site.xml:ro
      - ./nutch/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt:ro
      - ./nutch/seed.txt:/root/nutch/urls/seed.txt:ro
    # tty: true
    # command: bash
    ports:
      - 8080:8080

  searchkit:
    volumes:
      - ./searchkit/src:/app/src:ro
      - ./searchkit/public:/app/public:ro
    ports:
      - 35729:35729
      - 3000:3000

  kibana:
    ports:
      - 5601:5601

  ingress:
    volumes:
      - ./ingress/nginx.conf:/etc/nginx/nginx.conf:ro
